### ISSUE TITLE
Error adding plugin

### ISSUE THREAD

**Issue by blinder** [localytics/localytics-cordova#1]
First, apparently the phonegap repository is now gone (news to me), found this repository, tried to use the standard:  `cordova plugin add https://github.com/localytics/localytics-cordova.git`

got this:

```
Repository "https://github.com/localytics/localytics-cordova.git" checked out to git ref "master".
Error: ENOENT, no such file or directory '/var/folders/fs/z2042s0d7vj7f07gckwkyd2c0000gn/T/git/1439577480923/plugin.xml'
    at Object.fs.openSync (fs.js:439:18)
    at Object.fs.readFileSync (fs.js:290:15)
    at Object.module.exports.parseElementtreeSync (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/util/xml-helpers.js:118:27)
    at new PluginInfo (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/PluginInfo.js:320:37)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/plugins.js:45:30
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
```

Has support for Cordova/Phonegap been dropped by Localytics? Is there something else that should be used in place? 

I should also added that according to the README this:
`cordova plugin add https://github.com/localytics/phonegap.git`

that is no longer valid

**Comment by Shivagoy** [comment]
I am getting same error:
fatal: repository 'https://github.com/localytics/phonegap.git/' not found
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:134:23)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Socket.<anonymous> (child_process.js:979:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)

Please resolve this.

**Comment by ArtKuz** [comment]
Error:

```
Error during processing of action! Attempting to revert...
Failed to install 'com.localytics.phonegap.LocalyticsPlugin':Error: Uh oh!
"/home/artem/android/stretchit/platforms/android/libs/localytics.jar" already exists!
    at Object.module.exports.common.copyNewFile (/usr/local/node/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/common.js:67:19)
    at Object.module.exports.source-file.install (/usr/local/node/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/android.js:78:20)
    at installWrapper (/usr/local/node/lib/node_modules/cordova/node_modules/cordova-lib/src/platforms/platforms.js:77:32)
    at Object.ActionStack.process (/usr/local/node/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/action-stack.js:68:25)
    at handleInstall (/usr/local/node/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:576:20)
    at /usr/local/node/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:363:28
    at _fulfilled (/usr/local/node/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/node/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/node/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/local/node/lib/node_modules/cordova/node_modules/q/q.js:509:49
Error: Uh oh!
"/home/artem/android/stretchit/platforms/android/libs/localytics.jar" already exists!
    at Object.module.exports.common.copyNewFile (/usr/local/node/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/common.js:67:19)
    at Object.module.exports.source-file.install (/usr/local/node/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/android.js:78:20)
    at installWrapper (/usr/local/node/lib/node_modules/cordova/node_modules/cordova-lib/src/platforms/platforms.js:77:32)
    at Object.ActionStack.process (/usr/local/node/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/action-stack.js:68:25)
    at handleInstall (/usr/local/node/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:576:20)
    at /usr/local/node/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:363:28
    at _fulfilled (/usr/local/node/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/node/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/node/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/local/node/lib/node_modules/cordova/node_modules/q/q.js:509:49
```

**Comment by abashyam** [comment]
Please use the latest Cordova release. If there is still an issue open an issue with steps to recreate.
