### ISSUE TITLE
Android app crashes

### ISSUE THREAD

**Issue by thirappusuresh** [localytics/localytics-cordova#16]
Android application is crashing, attaching the stact trace
Fatal Exception: java.lang.NullPointerException
       at com.localytics.android.InAppManager._getInAppMessageMaps(InAppManager.java:1143)
       at com.localytics.android.InAppManager._getQualifiedInAppMessageForTrigger(InAppManager.java:1104)
       at com.localytics.android.InAppManager._inAppMessageTrigger(InAppManager.java:982)
       at com.localytics.android.MarketingHandler$13.run(MarketingHandler.java:642)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by abashyam** [comment]
The autoIntegrate issue has been resolved. Please upgrade to the latest release.
