### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by donny08** [localytics/localytics-cordova#9]
while running cordova plugin add https://github.com/localytics/localytics-cordova.git.I'm getting below error:
Error during processing of action! Attempting to revert...
Failed to install 'com.localytics.phonegap.LocalyticsPlugin':Error: Uh oh!
ENOENT: no such file or directory, open '/home/devuser/localdeals-html/plugins/com.localytics.phonegap.LocalyticsPlugin/www/Localytics.js'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at module.exports.common.js-module.install (/home/devuser/.node/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/common.js:136:36)
    at /home/devuser/.node/lib/node_modules/cordova/node_modules/cordova-lib/src/platforms/PlatformApiPoly.js:654:27
    at Object.ActionStack.process (/home/devuser/.node/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PlatformApiPoly.addPlugin (/home/devuser/.node/lib/node_modules/cordova/node_modules/cordova-lib/src/platforms/PlatformApiPoly.js:259:20)
    at handleInstall (/home/devuser/.node/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:603:6)
    at /home/devuser/.node/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:382:28
    at _fulfilled (/home/devuser/.node/lib/node_modules/cordova/node_modules/q/q.js:787:54)
Error: Uh oh!
ENOENT: no such file or directory, open '/home/devuser/localdeals-html/plugins/com.localytics.phonegap.LocalyticsPlugin/www/Localytics.js'

**Comment by donny08** [comment]
I had to delete the plugin  as well as platform folder and then  run **cordova plugin add https://github.com/localytics/localytics-cordova.git** command then rename '/home/devuser/localdeals-html/plugins/com.localytics.phonegap.LocalyticsPlugin/www/localytics.js file  to /home/devuser/localdeals-html/plugins/com.localytics.phonegap.LocalyticsPlugin/www/Localytics.js.

**Comment by bigwheels16** [comment]
This fix worked for me as well.  Please fix the filename in the repo.

**Comment by abashyam** [comment]
Is this still an issue with the latest SDK?

**Comment by abashyam** [comment]
Closing because of no activity.
